image:
  tag: "1.17.0"
  pullPolicy: IfNotPresent

service:
  http:
    # the Kubernetes service gitea-http'  service type
    type: NodePort 
    # the gitea-http service port
    port: 30950
    # this port will be used in port mappings to allow accessing the 
    # Gitea server from our laptops
    nodePort: 30950
gitea:
  # the admin credentials to access Gitea typically push/pull operations
  admin:
    # DON'T use username admin as its reserved and gitea will 
    # fail to start
    username: demo
    password: demo@123
    email: admin@example.com
  config:
    server:
      DISABLE_SSH: true
      # for this demo we will use http protocol to access Git repos
      PROTOCOL: http
      # the port gitea will listen on
      HTTP_PORT: 30950
      # The clone base url e.g. if repo is demo/foo the clone url will be 
      # $GITEA_URL/demo/foo
      ROOT_URL: "${GITEA_URL}"
    repository:
      DEFAULT_BRANCH: "${DAG_TARGET_VERSION}"
    webhook:
      # since we will deploy to local network we will allow all hosts
      ALLOWED_HOST_LIST: "*"
      # lets not do tls checks for local 
      SKIP_TLS_VERIFY: true
