destination:
  server: https://kubernetes.default.svc
source:
  repoURL: http://gitea-127.0.0.1.sslip.io:30950/user-01/dag.git
  targetRevision: k3s
gitea:
  server:
    outClusterURL: http://gitea-127.0.0.1.sslip.io:30950
    inClusterURL: 
  oAuthSecret: demo-oauth-user-01-secret
  username: user-01
  password: user-01@123
drone:
  server:
    version: 0.6.0
    host: http://drone-127.0.0.1.sslip.io:30980
    namespace: drone
    hostAliases:
      - ip: 10.43.175.122
        hostnames:
          - gitea-127.0.0.1.sslip.io
    admin:
      enable: true
argocd:
  imageUpdater:
    versio: 0.8.0
    logLevel: debug
    registries:
      - name: "k3d-k3d-myregistry.localhost"
        prefix: "k3d-k3d-myregistry.localhost:5000"
        api_url: "http://k3d-k3d-myregistry.localhost:5000"
        default: true
        defaultns: example
        insecure: true
artifactory:
    enabled: true