destination:
  server: https://kubernetes.default.svc
source:
  repoURL: http://kubernetes-vm..instruqt.io:30950/user-01/dag.git
  targetRevision: instruqt
gitea:
  server:
    outClusterURL: http://kubernetes-vm..instruqt.io:30950
    inClusterURL: 
  oAuthSecret: demo-oauth-user-01-secret
  username: user-01
  password: user-01@123
drone:
  docker:
    runner:
      insecureRegistries:
        - "nexus.infra.svc.cluster.local"
  server:
    version: 0.6.0
    host: http://kubernetes-vm..instruqt.io:30980
    namespace: drone
    # hostAliases:
    #   - ip: 
    #     hostnames:
    #       - kubernetes-vm..instruqt.io
    # admin:
    #   enable: true
argocd:
  imageUpdater:
    versio: 0.8.0
    logLevel: debug
    registries:
      - name: "nexus.infra.svc.cluster.local"
        prefix: "nexus.infra.svc.cluster.local"
        api_url: "http://nexus.infra.svc.cluster.local"
        default: true
        defaultns: example
        insecure: true
        credentials: "secret:infra/nexus3-config-c29mh65cmb#creds"